// Part 5: farming & crafting (sections 16-21) + sources
module.exports = [
  { t: 'pagebreak' },
  { t: 'part', text: 'Part 5 — Farming & Crafting Reference' },

  { t: 'h1', id: 'farm', text: '16. Where Every Item Comes From' },
  { t: 'p', text: '**Lair Keys** (Initiate bosses) only drop in Torment: War Plan Key Spoils, Helltide Tortured Gifts, World Bosses and Legions, Tree of Whispers caches, the Undercity. **Greater Lair Keys** drop more from **T6**. **Superior Lair Keys** come from Belial ambushes after you open a Hoard; at Belial you **choose which boss\'s loot table** to roll. Season Rank gives Key Rings at Ranks II–V. You can fight bosses any time; the **key opens the Hoard**.' },
  { t: 'table', widths: [2100, 900, 2800, 1700, 2580], head: ['Item', 'Slot', 'Where', 'Key', 'Trophy (5 → Unique)'], small: true, rows: [
    ['**Elegy**', 'Sword', '**Lord Zir**', 'Lair Key', 'Exquisite Blood'],
    ['**Infernal Homunculus**', 'Focus', '**Urivar**', 'Lair Key', 'Judicator\'s Mask'],
    ['**The Eightfold Idol**', 'Ring', '**Beast in the Ice**', 'Lair Key', 'Distilled Fear'],
    ['**Temerity**', 'Pants', '**Harbinger of Hatred**, or any Lair Boss (general pool)', 'Greater Lair Key', 'Abhorrent Heart'],
    ['**Wendigo Brand**', 'Ring', 'Any Lair Boss (general pool), or Cube Craft Unique on a white ring', '—', '—'],
    ['**Moloch\'s Beating Flame**', 'Amulet', '**The Butcher**', 'Greater Lair Key', 'Fresh Meat'],
    ['**Hand of Apotheosis**', 'Gloves', '**Bartuc**, at the end of Infernal Hordes', '666 Burning Aether → Compass', 'Chaotic Essence'],
    ['**Leoric\'s Crown**', 'Helm', 'World drop; best from the **S15 Capstone Waking Nightmares** (about 15%). Farm **Worldstone Keep**.', '—', '—'],
    ['Stone of Jordan', 'Ring', 'World drop; about 5% from S15 Capstones', '—', '—'],
    ['Anathema of the Primes', 'Charm', '**Andariel**, then Cube *Craft Unique Charm*', 'Greater Lair Key', 'Pincushioned Doll'],
    ['Ring of Starless Skies', 'Ring', 'Mythic, any uber boss', '—', '—'],
    ['Seal of the Diamond Mind', 'Seal', 'Mythic Seals (T10+, Mephisto)', '—', '—'],
  ] },
  { t: 'bullets', items: [
    '**Mythics:** since 3.2.1, Lair Bosses roll Mythics **from their own Unique pool**. **Belial** has the best Mythic rate and lets you choose the pool. **Echo of Mephisto** (Crux of the False Prophet) **guarantees a Mythic**. **Resplendent Sparks** come from Season Rank (up to 10), Mythic caches and salvaging Mythics.',
    '**Runes from bosses (Lair of Runes node):** Beast in the Ice drops Moni, Nagu, **Jah**. Butcher drops Qua, **Que**, Vex. Varshan drops Kry, Thul, **Tam**. Duriel drops Noc, Tam.',
  ] },

  { t: 'h1', id: 'craft', text: '17. Crafting Reference' },
  { t: 'h2', text: '17.1 Masterworking (Blacksmith)' },
  { t: 'bullets', items: [
    '**How it works:** Quality 0–25 adds **+1% to all affixes per point**. At 25 you get a **Capstone**: +50% to one random affix.',
    '**Reroll the capstone:** 850 IP costs 100 Obducite + 10M gold. 900 IP Ancestral costs 200 Obducite + 1 **Neathiron** + 10M. Two-handed weapons cost double.',
    '**Priority:** **weapons first**. Masterwork only Ancestral items. Steer capstones onto the MW targets in §13.',
    '**Obducite sources, best first:** NMD *Treasure Breach* sigils, Strongroom sigils, Undercity *Tribute of Refinement*, Infernal Hordes, Masterworking Caches from mercenary bartering.',
  ] },
  { t: 'h2', text: '17.2 Runewords (Horadric Cube; white base + runes)' },
  { t: 'table', widths: [2300, 2300, 2700, 2780], head: ['Runeword', 'Runes', 'Base', 'Used in'], rows: [
    ['**Stealth**', 'Tal + Eth', 'White chest', 'Starter'],
    ['**Ancient\'s Pledge**', 'Ral + Ort + Tal', 'White Focus', 'Starter'],
    ['**Enigma**', '**Jah + Ith + Ber**', 'White chest (use an Ancestral white base)', 'Speedfarm / Teleport'],
  ] },
  { t: 'p', text: '**Rune ladder (Cube):** 3 → 1 for Tir → Eth → Ith → Tal → Ral → Ort → Thul → Amn → Sol (some steps add a gem). 2 → 1 for Mal → Ist → Vex → Ohm → Lo → **Ber** → **Jah** (each step adds a gem, e.g. 2 Lo + Grand Topaz → Ber, 2 Ber + Grand Sapphire → Jah).' },
  { t: 'table', widths: [2300, 1500, 1700, 4580], head: ['Where', 'Ritual', 'Invocation', 'Effect'], rows: [
    ['Starter helm', 'Cir', 'Prid', 'Casting 5 skills casts Dark Prison automatically'],
    ['Starter chest', 'Moni', 'Qua', 'Stacking movement speed'],
    ['Midgame+ chest', 'Nagu', 'Que', 'Every skull counts as a summon; backup Barrier'],
    ['Endgame pants', 'Tam', 'Lac', 'Taunt + large damage reduction'],
    ['Speedfarm pants', 'Tam', 'Tir', 'Wrath on kill'],
  ] },
  { t: 'h2', text: '17.3 Mythics' },
  { t: 'bullets', items: [
    '**Cube "Upgrade to Mythic"** (Ancestral 900-IP Unique + 5 Resplendent Sparks) keeps every stat, temper and masterwork. **Only one "Crafted" Mythic can be worn**, and it won\'t work on transfigured (locked) items.',
    '**Jeweler Rune Crafting:** a random Mythic in a slot you choose. **Blacksmith Mythic Cache:** a random Mythic. S15 adds a second cache with Iconic Mythics only.',
    '**Priority:** Moloch\'s Beating Flame → Temerity → Leoric\'s Crown → Elegy → Infernal Homunculus. Hand of Apotheosis only as a Mythic with a 90%+ roll.',
  ] },

  { t: 'h1', id: 'survive', text: '18. Survival Checklist' },
  { t: 'bullets', items: [
    '**Barrier engine:** Temerity + Sadistic + Undying. You need all three once you run Destruction Demon.',
    '**Fire Resistance above 10,000:** you burn yourself with Fire, and Aspect of Scorching Heat scales from it.',
    '**Damage reduction:** Dark Prison: Chain Aura (45% from outside), Aspect of Diabolical Armor, the Abaddon\'s Flesh seal bonus, **Splinter of Pain** (+ Mother to cancel the slow), **Lac** and **Que** runes, **Raheir** and **Aldkin**.',
    '**Black Soulstone raises the damage you take** as it stacks. Never use it on Hardcore.',
    '**Max Life on nearly every item.** If you keep dying: drop one Torment tier, check resistances, move Paragon points toward defense.',
  ] },

  { t: 'h1', id: 'loop', text: '19. Your Repeating Endgame Loop' },
  { t: 'numbered', items: [
    'Claim finished **Season Rank**, **Whisper** and **War Plan** rewards.',
    'Run your **War Plan**: Undercity, Lair Bosses, Pit, Helltide, NMD. This earns keys, gear, materials and Destruction reputation.',
    '**Spend keys only on bosses that drop what you still need.** Greater keys and Husks go on Greater bosses and Belial.',
    '**Pit** for glyphs (10+ tiers above the glyph) and the next Torment unlock.',
    '**Capstone Waking Nightmares** for splinter reputation, Season Rank and Leoric\'s Crown. **Escalation NMDs** for Soul Splinters.',
    'Craft (Cube fixes, temper, masterwork), then test the next tier. Drop back if clear times double.',
    'Every **5 matching Boss Trophies**, craft a Unique in the Cube.',
  ] },

  { t: 'h1', id: 'extras', text: '20. Seasonal Extras and Secrets' },
  { t: 'bullets', items: [
    '**Uber Tristram:** put all **3 Prime Evil splinters** in the Cube to make **Wirt\'s Lucky Coins**. Use them at the Tristram fountain to fight all three Prime Evils. The reward is the **Hellfire Torch**, and the loot includes Mythics and Mythic charms.',
    '**Deckard\'s Journal** (10 pages). **Deckard\'s Memory** is a portal next to Cain that leads to Tristram side quests (Ogden\'s Sign, The Butcher, A Curious Monster).',
    '**Waking Nightmares** come in three sizes: Capstones (the Prime Evil fights), standard dungeons opened with a *Chronicle of Nightmares*, and surprise one-room pop-ups.',
    '**Moophisto** (World Boss) and the **Cow Level** are just for fun.',
  ] },

  { t: 'h1', id: 'mistakes', text: '21. Mistakes to Avoid' },
  { t: 'bullets', items: [
    'Equipping Infernal Homunculus before Elegy.',
    'Running Destruction Demon without Temerity + Sadistic (+ Undying).',
    'Using a non-Mythic, or under-90%, Hand of Apotheosis. Aspect of Ignition is better.',
    'Transfiguring an item you still want to upgrade to Mythic in the Cube. Making two Cube "Crafted" Mythics.',
    'Masterworking non-Ancestral items. Removing affixes after imprinting (Remove Affix is Magic/Rare only).',
    'Farming your highest unlocked Torment instead of the fastest safe one.',
    'Running activities outside your War Plan. Spending keys on bosses you don\'t need.',
    'Firing Blazing Scream into open space against bosses; use a wall.',
    'Wearing Hellfire and Anguish splinters together. Swapping Prime Evil splinters casually (it uses up the item).',
  ] },

  { t: 'h1', id: 'sources', text: 'Sources' },
  { t: 'links', items: [
    ['Your build page (couldn\'t be read automatically)', 'https://mobalytics.gg/diablo-4/builds/warlock-blazing-scream'],
    ['Maxroll – Blazing Scream Warlock Endgame Guide (S15)', 'https://maxroll.gg/d4/build-guides/blazing-scream-warlock-guide'],
    ['Maxroll – planner to4erl0e (decoded for this guide)', 'https://maxroll.gg/d4/planner/to4erl0e'],
    ['Maxroll – Blazing Scream Leveling Guide', 'https://maxroll.gg/d4/build-guides/blazing-scream-warlock-leveling-guide'],
    ['Maxroll – Season of Hell\'s Legacy guide', 'https://maxroll.gg/d4/resources/season-guide'],
    ['Maxroll – Endgame Progression', 'https://maxroll.gg/d4/meta/endgame-progression'],
    ['Maxroll – War Plans', 'https://maxroll.gg/d4/resources/war-plans'],
    ['Maxroll – Horadric Cube', 'https://maxroll.gg/d4/resources/horadric-cube'],
    ['Maxroll – Item Crafting', 'https://maxroll.gg/d4/resources/item-crafting'],
    ['D4Guides – Blazing Scream Endgame Build (S-Tier)', 'https://d4guides.gg/en/build/warlock-blazing-scream-endgame-build'],
    ['D4Guides – All 32 Soul Splinters', 'https://d4guides.gg/en/news/diablo-4-season-15-all-32-soul-splinters-explained'],
    ['D4Guides – Twelve new runes (S15)', 'https://d4guides.gg/en/news/diablo-4-season-15-twelve-new-runes-from-amn-to-tir'],
    ['D4Guides – Splinter of Destruction', 'https://d4guides.gg/en/database/season-powers/splinter-of-destruction'],
    ['D4Guides – Boss loot', 'https://d4guides.gg/en/bosses'],
    ['DiabloFilter – How to farm Soul Splinters', 'https://diablofilter.com/guide/the-best-way-to-target-farm-soul-splinters'],
    ['Helltides – Season 15 Splinters', 'https://helltides.com/tools/splinters'],
    ['timesaver – Season Rank guide', 'https://timesaver.gg/blog/diablo-4-season-15-season-journey-guide'],
    ['timesaver – Which splinter to choose', 'https://timesaver.gg/blog/diablo-4-season-15-prime-evil-splinter-which-to-choose'],
    ['Mythic Store – S15 endgame, level 70 to T12', 'https://mythic-store.com/blog/diablo-4-season-15-endgame-guide-from-level-70-to-torment-12'],
    ['expcarry – Torment guide', 'https://expcarry.com/diablo-4-torment-difficulty-guide'],
    ['Icy Veins – Runeword crafting in S15', 'https://www.icy-veins.com/d4/news/blizzard-has-quietly-shadow-dropped-rune-word-crafting-in-diablo-4-season-15/'],
    ['PC Gamer – Mercenaries', 'https://www.pcgamer.com/games/rpg/diablo-4-mercenaries-best-merc/'],
    ['Fextralife – The Pit', 'https://diablo4.wiki.fextralife.com/The+Pit+of+Artificers'],
  ] },
  { t: 'spacer' },
  { t: 'p', text: '*Per-slot stat pools, aspect slot rules, temper manual names and the Starter/Midgame/Endgame setups were extracted from the Season 15 (3.2.1) game data used by Maxroll\'s planner and from its decoded Blazing Scream profiles.*' },
];
