// Part 4: the build (sections 10-15)
module.exports = [
  { t: 'pagebreak' },
  { t: 'part', text: 'Part 4 — The Build' },

  { t: 'callout', kind: 'info', title: 'Where the build data comes from', body: [
    'Mobalytics blocks automated readers, so your exact page could not be read. The setups below come from **Maxroll\'s decoded planner** (every skill point, item, affix, temper, masterwork target and socket in 5 variants) and **D4Guides\' S-tier build**. The Mobalytics Blazing Scream pages describe the same build. Where the sites differ (§14 lists what to check), **follow your Mobalytics page for that detail**.',
  ] },

  { t: 'h1', id: 'how', text: '10. How Blazing Scream Works' },
  { t: 'bullets', items: [
    '**Blazing Scream** (Hellfire Core skill) sends demon skulls that **bounce off walls**. Aim into corridors; against bosses, aim at a wall behind them.',
    '**Elegy** makes Blazing Scream an **Archfiend** skill and gives **Skull Splitter** free. In S15 the small skulls deal the same damage as the main skull.',
    '**Infernal Homunculus** triggers all your **Lesser Demon upgrades** free on every Archfiend cast, including **Wrath generation and Vulnerable**.',
    '**The Eightfold Idol** lays **Sigil of Subversion** trails, which triggers the Nameless charm set and Sigil of Lava.',
    '**Metamorphosis: Destruction Demon** gives Demonform and **Volatility**, which **Moloch\'s Beating Flame** needs. Each Hellfire cast **raises your damage but burns you for 8% Max Life**. **Temerity + Sadistic + Undying** turn your overhealing into Barrier so you survive it.',
    '**Splinter of the Black Soulstone** stacks souls from demon deaths, up to +500% damage at Abyssal. You also take more damage. **Bombardment** stacks it fastest.',
  ] },

  { t: 'h1', id: 'starter', text: '11. Phase A — Starter Setup (Use Now; No Uniques)' },
  { t: 'kv', rows: [
    ['Soul Shard', '**Legion Shard + Sacrificial Fragment** (Unstoppable while you have Lesser Demons)'],
    ['Skill bar', 'Command Fallen · Blazing Scream · Rampage · Command Ae\'grom · Apocalypse · Nether Step'],
  ] },
  { t: 'table', widths: [2300, 900, 3800, 3080], head: ['Skill', 'Ranks', 'Modifiers', 'Variant'], rows: [
    ['Blazing Scream', '15', 'Impact Velocity, Damage', '**Skull Splitter**'],
    ['Apocalypse', '15', 'Double Blast, Survivor Damage', '**Annihilation**'],
    ['Nether Step', '15', 'Movement Speed, Damage Reduction', '**Shadow Recall**'],
    ['Rampage', '11', 'Lesser Demon Wrath, Elite Hit Chance', '**Abyssal Titan**'],
    ['Command Fallen', '8', 'Wrath, Dominance', '**Fallen Rush**'],
    ['Dark Prison', '1', 'Cooldown Reduction, Fortify', '**Chain Aura** (not on your bar; the **Prid** rune casts it)'],
  ] },
  { t: 'table', widths: [1300, 2900, 2500, 1800, 1580], head: ['Slot', 'Item / aspect', 'Key stats', 'Temper', 'Sockets'], small: true, rows: [
    ['Helm', 'Legendary, *Aspect of the Fortress*', 'Willpower, Life, Armor, +Demonology, CDR, Resource Gen', 'Max Life', '**Cir + Prid**'],
    ['Chest', '**Stealth** runeword (Tal + Eth)', 'Willpower, Life, Armor, Wrath/s, Cost Red., All Res', 'Max Life', '**Moni + Qua**'],
    ['Off-hand', '**Ancient\'s Pledge** runeword (Ral + Ort + Tal)', '—', 'Attack Speed', 'Ruby'],
    ['Weapon', '1H Sword, *Remorseless Aspect*', 'Willpower, Life, Fire Dmg, Damage, Crit Dmg', 'Attack Speed', 'Ruby'],
    ['Gloves', '*Aspect of Accursed Touch*', 'Willpower, Crit Chance, Attack Speed, Vulnerable, Fire, Crit Dmg, Life', 'Demonology Dmg', '—'],
    ['Pants', '*Aspect of Coagulation*', 'Willpower, Life, Armor, Wrath/s, All Res', 'Max Life', '2× Sapphire'],
    ['Boots', '*Aspect of Fiendish Oppression*', 'Move Speed, Willpower, Life, Wrath/s, +Rampage, Armor', 'Move Speed', '—'],
    ['Ring 1', '*Aspect of Scorching Heat*', 'Willpower, Life, AS, Vulnerable, Crit Chance, Dmg, Crit Dmg', 'Lucky Hit Resource', 'Splinter of **the Mother**'],
    ['Ring 2', '*Edgemaster\'s Aspect*', 'same as Ring 1', 'Lucky Hit Resource', 'Splinter of **Anguish**'],
    ['Amulet', '*Demonic Aspect*', 'Willpower, Life, Vulnerable, +Demonology, +All Skills, +Core, AS, Crit Chance', 'Lucky Hit Resource', 'Splinter of **the Black Soulstone**'],
    ['Talisman', 'Legendary Seal + **Fer, Phoba, Mlor of Slaughter** + Fer, Phoba of Practiced Technique', '—', '—', '—'],
  ] },
  { t: 'kv', rows: [
    ['Targets', 'More than 40% Attack Speed · more than 20% Crit Chance · Max Life everywhere · 3× Lucky Hit: Restore Resource'],
    ['Mercenaries', 'Hired: **Varyana** (*Bloodlust, Hysteria, Cleave, Bloodthirst*). Reinforcement: **Raheir** (*Bastion*), triggered on **Command Fallen**.'],
  ] },
  { t: 'p', text: '**Rotation:**' },
  { t: 'numbered', items: [
    '**Command Ae\'grom** to draw aggro.',
    '**Apocalypse** on the pack.',
    '**Command Fallen** ×3, recast when they expire.',
    '**Rampage** as a tank; recast to move it and turn on the Lesser Demon Wrath buff.',
    'Spam **Blazing Scream** into walls.',
    '**Nether Step** to move or escape.',
  ] },

  { t: 'h1', id: 'midgame', text: '12. Phase B — Midgame (Elegy + Infernal Homunculus + Temerity)' },
  { t: 'callout', kind: 'warn', title: 'Before you switch', body: [ { bullets: [
    'Don\'t equip Infernal Homunculus until you have **Elegy**.',
    'Don\'t run Destruction Demon without **Temerity + Sadistic Aspect** (and ideally Undying). The self-burn will kill you.',
    'Until you have **The Eightfold Idol**, cast Sigil of Subversion yourself.',
  ] } ] },
  { t: 'kv', rows: [
    ['Soul Shard', '**Vanguard Shard + Inferno Fragment** (Hellfire damage makes you radiate fire while Volatile in Demonform)'],
    ['Skill bar', 'Rampage · Dark Prison · Metamorphosis · Command Abodian · Molten Bomb · Blazing Scream'],
  ] },
  { t: 'table', widths: [2300, 900, 3800, 3080], head: ['Skill', 'Ranks', 'Modifiers', 'Variant'], rows: [
    ['Blazing Scream', '15', 'Impact Velocity, Damage', 'Skull Splitter (redundant with Elegy; the point can go to Rampage)'],
    ['Dark Prison', '15', 'Cooldown Reduction, Fortify', '**Chain Aura** (45% damage reduction from outside, 80% slow)'],
    ['Metamorphosis', '15', 'Damage Scaling, Dominance', '**Destruction Demon**'],
    ['Rampage', '15', 'Lesser Demon Wrath, Elite Hit Chance', '**Demonic Smash**'],
    ['Molten Bomb', '8', 'Wrath, Knock Down', '**Demon Turret**'],
  ] },
  { t: 'table', widths: [1300, 3300, 5480], head: ['Slot', 'Item', 'Notes'], small: true, rows: [
    ['Helm', '**Leoric\'s Crown**', 'Holds 2 Soul Splinters: **Black Soulstone + Anguish**'],
    ['Chest', 'Legendary, *Aspect of Diabolical Armor*', 'Runes **Nagu + Que**'],
    ['Off-hand', '**Infernal Homunculus**', 'Royal Ruby'],
    ['Weapon', '**Elegy**', 'Royal Ruby'],
    ['Gloves', 'Legendary, *Aspect of Ignition*', 'Until a Mythic Hand of Apotheosis with a 90%+ roll'],
    ['Pants', '**Temerity**', '2× Royal Sapphire'],
    ['Boots', 'Legendary, *Sadistic Aspect*', 'Heals on kills; the overheal feeds Temerity\'s Barrier'],
    ['Ring 1', 'Legendary, *Demonic Aspect*', 'Splinter of **Pain**'],
    ['Ring 2', '**The Eightfold Idol**', 'Splinter of **Damnation**'],
    ['Amulet', '**Moloch\'s Beating Flame**', 'First Mythic target · Splinter of **the Mother**'],
    ['Talisman', 'Legendary Seal (+1 Charm Slot, Crit Chance, Abaddon\'s Flesh bonus)', '**Linta, Phoba, Berú, Fer, Mlor of Abaddon\'s Flesh** + **Anathema of the Primes**'],
  ] },
  { t: 'kv', rows: [
    ['Targets', '100% Attack Speed · 100% Crit Chance · more than 10 Wrath/s · Max Life everywhere · 2× Lucky Hit Resource · more than 10,000 Fire Resistance'],
    ['Mercenaries', 'Hired: **Varyana** (*Taste of Flesh, Hysteria, Whirlwind, Cleave*). Reinforcement: **Raheir** (*Bastion*) on **Blazing Scream**.'],
  ] },
  { t: 'p', text: '**Rotation:**' },
  { t: 'numbered', items: [
    'Ride **Command Abodian** into packs; recast to dismount.',
    'Cast **Metamorphosis** once; recast only if it drops.',
    '**Dark Prison** while fighting (kills reset it).',
    '**Molten Bomb** for Wrath.',
    'Spam **Blazing Scream** into walls.',
    'Stay close for the Inferno Fragment.',
  ] },

  { t: 'h1', id: 'endgame', text: '13. Phase C — Endgame, Push and Speedfarm' },
  { t: 'kv', rows: [
    ['Skill bar', 'Sigil of Subversion · Dark Prison · Metamorphosis · Command Abodian · Molten Bomb · Blazing Scream'],
    ['Skill points', 'The Midgame points, with Rampage at 11 (same modifiers and variant), plus **Sigil of Subversion** at 1 rank (Movement Speed, Slow, **Sigil of Lava**)'],
  ] },
  { t: 'p', text: '★ = Greater Affix. **MW** = the affix to aim your masterwork capstone at.' },
  { t: 'table', widths: [1100, 1900, 3200, 1300, 1400, 1180], head: ['Slot', 'Item', 'Key affixes', 'MW', 'Temper', 'Sockets'], small: true, rows: [
    ['Helm', '**Leoric\'s Crown** (Mythic)', 'Attack Speed★, Willpower, Life, Armor, +Demonology, CDR', 'Attack Speed', 'Max Life★', 'Abyssal Black Soulstone + Abyssal Anguish'],
    ['Chest', '*Aspect of Diabolical Armor*', 'Wrath/s★, Willpower, Armor, Life, All Res, Healing', 'Wrath/s', 'Max Life★', 'Nagu + Que'],
    ['Off-hand', '**Infernal Homunculus** (Mythic)', 'Weapon Dmg★, Life, Crit Chance, +Demonology, Crit Dmg, Fire, Cost Red.', 'Crit Chance', 'Crit Chance★', 'Horadric Ruby'],
    ['Weapon', '**Elegy** (Mythic)', 'Weapon Dmg★, Life, Crit Dmg, +4 Blazing Scream, Fire, Dmg, Willpower, Lucky Hit Resource', 'Weapon Dmg', 'Crit Chance★', 'Horadric Ruby'],
    ['Gloves', '**Hand of Apotheosis** (Mythic, 90%+)', 'Crit Dmg★, Life, Vulnerable, Fire, Crit Chance, +4 Blazing Scream, AS, Life on Hit', 'Crit Dmg', 'Demonology Dmg★', '—'],
    ['Pants', '**Temerity** (Mythic)', 'Willpower★, Life, Armor, All Res, Wrath/s, Healing, Fire Res', '—', 'Max Life★', 'Tam + Lac'],
    ['Boots', '*Undying Aspect*', 'Wrath/s★, Move Speed, Life, +Hellfire, Willpower, Armor', 'Wrath/s', 'Move Speed★', '—'],
    ['Ring 1', '**Wendigo Brand** (Mythic)', 'Attack Speed★, Life, Crit Dmg, Vulnerable, Willpower, Fire', 'Attack Speed', 'Lucky Hit Res.★', 'Abyssal Pain'],
    ['Ring 2', '**The Eightfold Idol** (Mythic)', 'Crit Dmg★, Willpower, Life, Crit Chance, Vulnerable, Fire', 'Crit Dmg', 'Lucky Hit Res.★', 'Abyssal Damnation'],
    ['Amulet', '**Moloch\'s Beating Flame** (Mythic) + *Sadistic*', 'Crit Dmg★, Vulnerable, +3 Hellfire, +3 All Skills, +3 Demonology, Life, Willpower, Crit Chance', 'Crit Dmg', 'Cost Red.★', 'Abyssal Mother'],
    ['Talisman', '**Seal of the Diamond Mind** (Mythic Seal)', 'Linta, Berú, Fer, Mlor of Abaddon\'s Flesh + Fer, Berú of the Nameless. Each: +3 Hellfire and one resistance.', '—', '—', '—'],
  ] },
  { t: 'bullets', items: [
    '**Sadistic on the amulet:** Maxroll\'s planner puts Sadistic on Moloch\'s. This is almost certainly a Cube **Transfigure with a Kullean Tuning Prism**, which adds a random Utility aspect to an amulet. **Make the amulet Mythic first**, because transfiguring can lock the item and the Cube upgrade can\'t be used on locked items. This frees the boots for Undying.',
    '**Seal of the Diamond Mind** grants the Phoba of the Nameless 3-piece bonus: damage and damage reduction when you activate a Sigil. The Eightfold Idol\'s trails trigger it.',
    '**Resistances:** Fire first, then whichever your jewelry lacks. If your charms don\'t cover a gap, swap Wendigo Brand for **Stone of Jordan**.',
    '**Push variant:** put **Bombardment** on the bar (1 rank: Additional Demon, Telekinesis, **Endless Barrage**; Molten Bomb drops to 4). Use *Aspect of Rallying Reversal* on boots (+20% Attack Speed; don\'t overcap). Keep the 5-stack Endless Barrage buff for Black Soulstone and Wendigo stacks.',
    '**Speedfarm variant:** **Enigma** chest (Evade becomes Teleport). Pants runes **Tam + Tir** (Wrath on kill). Fire-resistance charms. Optional: Anathema of the Primes makes Rampage cost Wrath instead of Dominance.',
    '**Mercenaries:** hired **Raheir** (*Provoke, Shield Charge, Raheir\'s Guard, Iron Wolf\'s Ward*); reinforcement **Aldkin** (*Field of Languish*) on **Blazing Scream**.',
  ] },

  { t: 'h1', id: 'orbital', text: '14. The Orbital Scream / Teleport Version (Likely Your Mobalytics Page)' },
  { t: 'p', text: 'Mobalytics\' Blazing Scream pages and D4Guides\' S-tier "Farm-Lock" describe this: *"Activate Blazing Scream: Orbital Scream and keep it going, move around by pressing Evade to Teleport, cast Bombardment: Endless Barrage while you teleport, and use Dark Prison: Chain Aura on cooldown."*' },
  { t: 'check', items: [
    'Blazing Scream variant: **Orbital Scream** (this section) or Skull Splitter (Maxroll, §12–13)?',
    'Skill bar: **Bombardment + Command Fallen** (this section) or Command Abodian + Molten Bomb?',
    'Chest: **Enigma**?',
    'Paragon boards and glyphs: see §15. The sites differ here.',
    'Boots: Sadistic or Undying?',
  ] },
  { t: 'table', widths: [2300, 900, 3800, 3080], head: ['Skill (83 pts)', 'Ranks', 'Modifiers', 'Variant'], rows: [
    ['Blazing Scream', '15', 'Impact Velocity, Damage', '**Orbital Scream** (orbits you 10s; Elegy still gives Skull Splitter)'],
    ['Bombardment', '15', 'Damage, Telekinesis', '**Endless Barrage**'],
    ['Dark Prison', '15', 'Cooldown Reduction, Fortify', '**Chain Aura**'],
    ['Metamorphosis', '15', '—', '**Destruction Demon**'],
    ['Sigil of Subversion', '6', 'Movement Speed, Slow', '**Sigil of Lava**'],
    ['Command Fallen', '1', 'Wrath, Lifetime Damage', '**Meat Shields**'],
  ] },
  { t: 'p', text: '*D4Guides lists these modifiers without their parent skills. I matched each to its skill using the game\'s skill data; the total comes to exactly 83 points.*' },
  { t: 'bullets', items: [
    '**Gear:** Leoric\'s Crown, **Enigma**, Hand of Apotheosis, Temerity, **Sadistic** boots (Undying optional), Moloch\'s Beating Flame, Wendigo Brand + The Eightfold Idol, Elegy + Infernal Homunculus. Que rune optional for extra Barrier. For max-damage pushing, D4Guides recommends **Ring of Starless Skies** for resource.',
    '**Rotation:** Orbital Scream → Metamorphosis → Dark Prison → **hold Bombardment** and keep **teleporting** (Evade) through packs. Refresh Orbital Scream before 10s. Low on Wrath? Release Bombardment and **hold Command Fallen while teleporting**, then return to Bombardment.',
    '**Mercenary:** Raheir.',
  ] },

  { t: 'h1', id: 'paragon', text: '15. Paragon Boards and Glyphs' },
  { t: 'table', widths: [500, 2200, 3300, 2100, 1980], head: ['#', 'Board', 'Placement', 'Glyph', 'Legendary node'], rows: [
    ['1', '**Start**', '—', '**Superiority** (new in S15)', '—'],
    ['2', '**Dynamism**', 'Above Start', '**Attrition**', 'Dynamism'],
    ['3', '**Fathomless**', 'Left of Dynamism', '**Unbound**', 'Fathomless'],
    ['4', '**Demonic Spicules**', 'Left of Fathomless, rotated once (90°)', '**Demonologist**', 'Demonic Spicules'],
    ['5', '**Greater Hex**', 'Below Demonic Spicules, rotated 3× (270°)', '**Archfiend**', 'Greater Hex'],
  ] },
  { t: 'bullets', items: [
    '**Node paths:** open Maxroll\'s planner (maxroll.gg/d4/planner/to4erl0e), Paragon tab. It has steps at about 230, 230, 280 and all points. You get up to 300 Paragon levels plus 42 points from Season Rank.',
    '**Rules:** survivability before damage early · Legendary nodes ASAP · meet glyph attribute requirements rather than maxing them · finish boards before going back for small nodes.',
    '**Glyph order:** **Superiority → Attrition → Unbound → Demonologist → Archfiend**. All to 50, then 100, then 150. Superiority and Attrition need 50 for the Intelligence requirements.',
    '**Alternative layout (D4Guides, maybe Mobalytics):** Start, Demonic Spicules, Ritualism, Fathomless, Dynamism, with glyphs **Eldritch Sight, Demonologist, Unbound, Hellforge, Attrition**.',
    '**Leveling glyphs:** only in the Pit, 3–4 upgrade attempts per clear (+1 for no deaths). Run a Pit tier **10+ above the glyph** for guaranteed upgrades; 0–5 above is 70%. Urn of Glyphs and the Pit War Plan nodes add attempts.',
  ] },
];
