// Part 3: Season 15 systems (sections 6-9)
module.exports = [
  { t: 'pagebreak' },
  { t: 'part', text: 'Part 3 — Season 15 Systems' },

  { t: 'h1', id: 'quest', text: '6. Finish the Seasonal Questline and Choose Your Splinter' },
  { t: 'p', text: 'Deckard Cain gives the quests at the **Imperial Library (Caldeum, Kehjistan)**. You already have the Splinter of Destruction, so quest 2 is done.' },
  { t: 'table', widths: [500, 1900, 2500, 3280, 1900], head: ['#', 'Quest', 'Where it starts', 'What you fight', 'Reward'], rows: [
    ['1', 'Refuge from the Memories ✔', 'Kuhuthi\'s Tavern, **Tarsarak**', 'Demons in the tavern, then you meet Cain', '—'],
    ['2', 'The Horadrim\'s Fate ✔', 'Cain at the ruined Imperial Library; Tal Rasha outside ruined **Nostrava**', '"Diablo II – Worldstone Keep": the Ancients, then **Echo of Baal**', '**Splinter of Destruction** ✔'],
    ['3', '**The Burning Shepherd**', '**Sankekur**, south of **Rakhat Keep**, Hawezar', '"Diablo II – Durance of Hate": the High Council, then **Echo of Mephisto**', 'Splinter of Hatred'],
    ['4', '**The Brother\'s Keeper**', '**Aidan** at a ruined church in **Scosglen**', '"Diablo – The Labyrinth": the Butcher, Blood Raven, then **Echo of Diablo** (Aidan fights with you)', 'Splinter of Terror'],
    ['5', '**Legacy of Hope**', 'Cain, Imperial Library', 'Place the last splinter on **Deckard\'s Table**, then **choose one splinter**', 'Prime Evil Power + reputation track'],
  ] },
  { t: 'callout', kind: 'tip', title: 'Keep the Splinter of Destruction', body: [ { bullets: [
    '**It boosts what you farm:** the Undercity and Lair Bosses. That means extra Boss Trophies, extra runes from bosses, more Nemesis portals and **+3 Uniques in Hoard chests** (§7).',
    '**Its power helps the build:** rank 6 gives **+50 Wrath** per proc, and rank 16 applies **Vulnerable**.',
    '**The standard plan:** Destruction while gearing. **Hatred** (Pit and glyph bonuses) only once you\'re geared and just pushing the Pit.',
  ] } ] },
  { t: 'table', widths: [2100, 1300, 1300, 3080, 2300], head: ['Splinter', 'Prime Evil', 'Element', 'Boosts', 'Best for'], rows: [
    ['**Destruction** (yours)', 'Baal', 'Cold', '**Undercity, Lair Bosses**, Whispers', 'Farming uniques, leveling'],
    ['Terror', 'Diablo', 'Fire', 'Helltide, Infernal Hordes, Whispers', 'Helltide / Hordes players'],
    ['Hatred', 'Mephisto', 'Physical', 'Pit, Nightmare Dungeons, Whispers', 'Glyphs, Pit pushing, Resplendent Sparks'],
  ] },
  { t: 'bullets', items: [
    '**Swapping:** splinters are consumables. Right-click a different one to replace yours; it is **used up**. Extra splinters are rare and best farmed from the Capstone Waking Nightmares. Baal\'s "Worldstone Keep (Hell)" clears in about 2–4 min.',
    '**Prime Evil Ambushes:** while you carry a splinter, Echoes of Baal, Diablo or Mephisto can spawn after local events or Whispers, after a 10-second warning. They drop loot, and Baal\'s echoes hit you harder.',
  ] },

  { t: 'h1', id: 'splinter', text: '7. Splinter of Destruction: How to Level It and What You Get' },
  { t: 'p', text: '**Ice of Excidium** periodically fires a blast of ice for **1500% Cold damage**, plus small projectiles for 300% each. You earn reputation in **Waking Nightmares**, by killing *Remnants of Destruction*, and in the Undercity and Lair Bosses. When the bar fills, rank up at **Deckard\'s Table** (Imperial Library). Max rank is **24** (20,000 rep), roughly 10–15 hours.' },
  { t: 'table', widths: [900, 1100, 8080], head: ['Rank', 'Rep', 'Reward'], small: true, rows: [
    ['1', '1', '**Ice of Excidium** (the power)'],
    ['2', '350', '**Siege Engine**: procs can grant Undercity Attunement'],
    ['3', '450', 'Currency Cache'],
    ['4', '666', 'Small Armory Cache + War Plan bonus **Jade Epiphany** (Undercity): +50% XP orbs, +1 Monster Power'],
    ['5', '950', 'Solemn Reflection + **Grim Retribution** (Whispers): more Whisper Ambushes'],
    ['6', '1,300', '**Cold Blood: +50 Wrath per proc (get this on day one)**'],
    ['7', '1,850', 'Mystery Archetype Cache'],
    ['8', '2,600', 'Solemn Reflection + **Endless Swarm** (Undercity): Invasion Portal on each floor'],
    ['9', '3,650', 'Currency Cache'],
    ['10', '5,150', '**Grisly Trophies**: 30% chance for an **extra Boss Trophy**'],
    ['11', '7,200', 'Solemn Reflection'],
    ['12', '9,650', '**Last Gasp** (Undercity): triggers at 15 seconds or less'],
    ['13', '10,500', 'Masterwork Cache'],
    ['14', '11,400', 'Ancient Memory + **Lair of Runes**: Lair Bosses drop extra runes'],
    ['15', '12,300', 'Mystery Archetype Cache'],
    ['16', '13,100', '**Seizing Frost**: procs Chill 10% and make enemies **Vulnerable** for 5s'],
    ['17', '14,000', 'Masterwork Cache'],
    ['18', '14,800', 'Ancient Memory + **Two by Two**: higher Nemesis Lair portal chance'],
    ['19', '15,700', 'Mystery Greater Archetype Cache'],
    ['20', '16,600', 'Greater Lair Cache + **Exotic Armory**: Hoard chests drop **3 extra Uniques**'],
    ['21', '17,400', '**Shattered Flesh**: first hit deals 20% of the enemy\'s Max Life over 4s'],
    ['22', '18,300', 'Ancient Memory + **Colossal Foe**: Boss Ambushes +2 Monster Power, drop Superior Lair Keys'],
    ['23', '19,100', 'Mystery Greater Archetype Cache'],
    ['24', '20,000', '**Thrill of Ruin** (bursts of extra blasts) + **Resplendent Cache** (includes a Resplendent Spark)'],
  ] },
  { t: 'p', text: '**War Plan synergy:** the named bonuses only work **while Destruction is equipped**, and only on those War Plan nodes: Jade Epiphany, Endless Swarm, Last Gasp, Lair of Runes, Two by Two, Exotic Armory, Grim Retribution and Colossal Foe. Take those nodes.' },

  { t: 'h1', id: 'ranks', text: '8. Season Rank Ladder (I–IX) and Season Blessings' },
  { t: 'p', text: '9 ranks, 125+ objectives. Clear a rank\'s **Capstone** to advance. All ranks together give **14 Skill Points** and **42 Paragon Points**; the build assumes 83 skill points. You also get **10 Resplendent Sparks**, **5 Mythic Unique Caches**, Lair Key Rings, Forgotten Souls, Obducite and Neathiron.' },
  { t: 'table', widths: [700, 2600, 3500, 3280], head: ['Rank', 'Capstone', 'Pit / glyph gates in objectives', 'Notable rewards'], small: true, rows: [
    ['I', '**Halls of the Blind** (Expert+)', '—', '1 Skill Point, Archetype Cache, Ashes'],
    ['II', '**Den of Evil** (Penitent+)', '—', '2 Skill Points, **Lair Key**, Ashes. War Plans reputation starts here.'],
    ['III', '**Scouring of Caldeum** (T1+)', 'Pit 10 (unlocks T1)', '3 Skill Points, 4 Paragon, **Lair Key Ring**'],
    ['IV', '**Horadric Library** (T2+)', 'Pit 15, one glyph at 10', '3 Skill Points, 4 Paragon, **Greater Lair Key Ring**'],
    ['V', '**Worldstone Keep – Nightmare** (T4+)', 'Pit 25, three glyphs at 20, masterwork 10 items to 10, temper 16 Ancestrals', '4 Paragon, **Superior Lair Key Ring**, Liquid Rainbow'],
    ['VI', '**Durance of Hate – Nightmare** (T6+)', 'Clear 6 standard Waking Nightmares on T5', '**1 Resplendent Spark**, 4 Paragon, Dark Wanderbear pet'],
    ['VII', '**The Labyrinth – Nightmare** (T8+)', 'Pit 60, three glyphs at 45, Harbinger/Duriel/Andariel', '4 Paragon, **Crux of the False Prophet**, Mythic Unique cache'],
    ['VIII', '**Echo of Mephisto on T10** (Lord of Hatred)', 'Pit 80, three glyphs at 50, Paragon 250, all 3 Echoes on T10', '1 Resplendent Spark, Mythic cache, title "Deckard\'s Confidant"'],
    ['IX', '**10 of 24 challenges** (mostly T11–T12)', '—', '**3 Resplendent Sparks**, Mythic Archetype Cache, Neathiron'],
  ] },
  { t: 'p', text: '**Fastest order:** Ranks I–III first (skill points and Lair Keys), then **Rank V** (T4), then level glyphs, then push to **Rank VIII**. Run the Capstone Waking Nightmares often; they complete several ranks\' objectives and give splinter reputation.' },
  { t: 'h2', text: '8.2 Season Blessings (Smoldering Ashes)' },
  { t: 'numbered', items: [
    '**Urn of Reclamation:** better salvage materials. Best while gearing.',
    '**Urn of Glyphs:** extra glyph upgrade chance in the Pit. Best long-term pick, since glyph levels gate Ranks IV–VIII.',
    '**Urn of Masterworking:** extra Obducite.',
    'Urn of Curiosities (second item from Purveyor gambles) and Urn of Ancestral Whispers (Ancestral caches from the Tree of Whispers) when you can afford them.',
  ] },

  { t: 'h1', id: 'systems', text: '9. Systems to Set Up Right After the Campaign' },
  { t: 'h2', text: '9.1 Temis (Skovos), the Lord of Hatred hub' },
  { t: 'bullets', items: [
    '**War Plans:** Tyrael\'s table.',
    '**Horadric Cube:** unlocked in the campaign quest "Doorways to the Distant Past".',
    '**Echoing Hatred:** endless horde mode, entered with a *Trace of Echoes* at the Sightless Eye. It\'s a final exam, not gearing content.',
  ] },
  { t: 'h2', text: '9.2 War Plans: never play outside your plan' },
  { t: 'p', text: 'A War Plan is a playlist of up to **5 activities**. **Activity XP only counts for activities in your active War Plan.** Each activity has a 7-level tree with 1 point per level. Suggested plan: **Undercity, Lair Bosses, the Pit, Helltide, Nightmare Dungeons**. Swap in Infernal Hordes when farming Bartuc. The Lair Boss tree needs T1+; Greater Lair Boss nodes need T6+.' },
  { t: 'table', widths: [2200, 7880], head: ['Tree', 'Node order (★ = gets a Destruction bonus)'], rows: [
    ['Lair Bosses', '**Two by Two★** → Greater Nemesis → **Lair of Runes★** → **Exotic Armory★**'],
    ['Undercity', '**Endless Swarm★** → Unfortunate Souls → Gutter Filth → **Jade Epiphany★** → Finely Tuned → Pathfinder → Initiative (also **Last Gasp★**)'],
    ['Pit', 'Choron\'s Blessing → Choron\'s Haste (extra glyph upgrades) → Heart of Stone → Damned Thieves'],
    ['Helltide', 'Hellmouth → Writhe and Rot (XP + Lair Keys) → Wretched Vermin'],
    ['Nightmare Dungeons', 'Waking Spoils → Gauntlet → Fearless Conviction → … → **Branching Pathways** (choose floor bonuses for Soul Splinter farming)'],
    ['Whispers', 'Tree of Plenty → Wisdom of Whispers → Grim Mysteries → Resplendent Favor → **Grim Retribution★** → **Colossal Foe★**'],
  ] },
  { t: 'callout', kind: 'warn', title: 'Known bug (Maxroll, Aug 2026)', body: [ 'The Lair Boss node **"Infernal Deception"** spawned a Belial that dropped no loot. Skip it unless you know it\'s been fixed.' ] },
  { t: 'h2', text: '9.3 Talismans' },
  { t: 'bullets', items: [
    'The **Seal** sets your charm slots: Magic 3, Rare 4, **Legendary 5**, Mythic 6. Some roll **+1 Charm Slot**. You can\'t use charms without a Seal.',
    '**Set charms** give set bonuses: **Abaddon\'s Flesh** (Warlock), plus **the Nameless** at endgame. **Unique charms** carry a Unique item\'s power, and can be Mythic in S15 (+30% power).',
    'Salvage spare charms and Seals at the Occultist for Infused Horadric Resin. *Reroll Set Charm* in the Cube is how you get Greater Affixes on charms.',
  ] },
  { t: 'h2', text: '9.4 Mercenaries (The Den, Nahantu)' },
  { t: 'bullets', items: [
    '**Raheir** (tank) joins in the Vessel of Hatred campaign.',
    '**Varyana** (berserker): the "Brutal Note" in The Den after clearing the **Temple of Rot** stronghold (Dry Steppes). It starts the quest "Slayer\'s Retribution".',
    '**Aldkin** (cursed child): quest "A Nameless Mystery" in Nahantu. **Subo** (archer): "A Feather on the Scale" in Hawezar; not used here.',
    'You get 1 hired mercenary + 1 reinforcement. Set the reinforcement to trigger on a skill you cast often.',
  ] },
  { t: 'h2', text: '9.5 Codex of Power, Occultist and Jeweler' },
  { t: 'bullets', items: [
    '**Aspects:** salvage Legendaries to unlock or upgrade aspects, then imprint them at the Occultist. Non-Ancestral: 15 Baleful Fragment + 250k gold. Ancestral: 25 Forgotten Soul + 1M gold.',
    '**Enchanting:** rerolls one affix per item. The item becomes account-bound, and the cost climbs each time.',
    '**Sockets (Jeweler):** Ancestral costs 1 Scattered Prism + 150k gold. Helm, chest and pants can have 2.',
  ] },
  { t: 'h2', text: '9.6 The Pit and Torment tiers' },
  { t: 'p', text: '**Artificer\'s Obelisk, just north of the Cerrigar waypoint** (Scosglen). Entry costs **Artificer\'s Stones** (Whispers, NMDs, Helltides, Legion events). **Only Pit clears unlock Torment tiers.**' },
  { t: 'table', widths: [1400, 1900, 6780], head: ['Torment', 'Pit clear', 'What changes'], small: true, rows: [
    ['I', '10 (lvl 70)', '**Ancestral items and Greater Affixes** start dropping; Lair Bosses open'],
    ['II', '15', 'More Legendary temper manuals and Scrolls of Restoration'],
    ['III', '20', 'More set charms'],
    ['IV', '25', 'More Neathiron'],
    ['V', '30', 'More Legendary runes'],
    ['VI', '40', '**More Greater Lair Keys** (Butcher, Harbinger)'],
    ['VII', '50', 'More Volatile Primordial Dust'],
    ['VIII', '60', 'More Unique charms'],
    ['IX', '70', 'More Kullean Tuning Prisms'],
    ['X', '80', 'More Mythic Horadric Seals and better Mythic Tribute odds. **A realistic long-term farm tier.**'],
    ['XI–XII', '90 / 100', 'Mostly more XP and gold'],
  ] },
  { t: 'p', text: 'Mythic drop chance scales with Torment, from about 0.05% at T1 to 0.4% at T12 (a community estimate). **Unlock as high as you can push, but farm the highest tier that is still fast.**' },
];
